// Generated by CoffeeScript 1.4.0
var Journey;

Journey = Backbone.Collection.extend({
  _observing: false,
  _hash: null,
  model: app.models.SERPTripSelected,
  initialize: function() {
    this.on('add', this.instantiateCollections, this);
    return app.log('[app.collections.Journey]: initialize');
  },
  observe: function() {
    this._observing = true;
    return app.socket.on('selected_list_fetch_ok', _.bind(this.fetched, this));
  },
  setHash: function(_hash) {
    this._hash = _hash;
    return this;
  },
  fetched: function(resp) {
    var data;
    if (resp.trip_hash !== this._hash) {
      return;
    }
    data = resp.items;
    this.add(data);
    this.trigger('fetched', data);
    return app.log('[app.collections.SERPTrips]: fetched', data);
  },
  instantiateCollections: function(model) {
    if (this._observing) {
      return model.observe();
    }
  },
  _dump: function(json) {
    var item, _i, _len, _ref, _ref1;
    for (_i = 0, _len = json.length; _i < _len; _i++) {
      item = json[_i];
      item.hotel = (_ref = item.hotel) != null ? _ref.toJSON() : void 0;
      item.flight = (_ref1 = item.flight) != null ? _ref1.toJSON() : void 0;
    }
    return json;
  },
  serialize: function() {
    return this._dump(this.toJSON());
  }
});

app.collections.Journey = Journey;
