// Generated by CoffeeScript 1.4.0
(function() {
  var Trips;

  Trips = Backbone.Collection.extend({
    model: app.models.TripsStop,
    initialize: function() {
      return app.log('[app.collections.Trips]: initialize');
    }
  });

  app.collections.Trips = Trips;

}).call(this);
