// Generated by CoffeeScript 1.4.0
(function() {
  var Index;

  Index = Backbone.View.extend({
    initialize: function() {
      this.render();
      return this;
    },
    render: function() {
      $('#page-index .block-current').hide();
      $('#page-index .block-current').html(app.templates.searchform(this.model.toJSON()));
      $('#page-index .block-current').fadeIn(500);
      return this;
    }
  });

  app.views.index = Index;

}).call(this);
