// Generated by CoffeeScript 1.4.0
(function() {
  var chai, eviterra, expect, ostrovok;

  chai = require('chai');

  chai.should();

  expect = chai.expect;

  ostrovok = require('./../app/server/providers/ostrovok');

  describe('Ostrovok', function() {
    describe('#autocomplete', function() {
      return it('should work with "Москва" input', function(done) {
        return ostrovok.autocomplete("Москва", function(err, result) {
          expect(err).to.be.equal(null);
          result.length.should.equal(3);
          expect(result[0]).to.be.deep.equal({
            name: 'Москва',
            oid: 2395,
            country: 'Россия',
            displayName: 'Москва',
            provider: 'ostrovok'
          });
          return done();
        });
      });
    });
    return describe('#search', function() {
      return it('should find something in Moscow', function(done) {
        var destination, extra, origin;
        destination = {
          oid: 2395,
          date: '2013-02-07'
        };
        origin = {
          date: '2013-02-01'
        };
        extra = {
          page: 1,
          adults: 2
        };
        return ostrovok.search(origin, destination, extra, function(error, hotels) {
          expect(error).to.be.equal(null);
          expect(hotels.results.length).to.be.above(0);
          if (hotels.complete) {
            return done();
          }
        });
      });
    });
  });

  eviterra = require('./../app/server/providers/eviterra');

  describe('Eviterra', function() {
    describe('#autocomplete', function() {
      return it('should work with "Москва" input', function(done) {
        return eviterra.autocomplete("Москва", function(err, result) {
          expect(err).to.be.equal(null);
          expect(result[0]).to.be.deep.equal({
            name: 'Москва',
            iata: 'MOW',
            country: 'Россия',
            displayName: 'Москва',
            provider: 'eviterra'
          });
          return done();
        });
      });
    });
    return describe('#search', function() {
      return it('should find MOW -> LED flights', function(done) {
        var destination, extra, origin;
        destination = {
          iata: 'LED'
        };
        origin = {
          iata: 'MOW',
          date: '2013-02-07'
        };
        extra = {
          adults: 2
        };
        return eviterra.search(origin, destination, extra, function(err, results) {
          expect(err).to.be.equal(null);
          console.log(results);
          return done();
        });
      });
    });
  });

}).call(this);
