// Generated by CoffeeScript 1.4.0
(function() {
  var Search;

  Search = Backbone.Model.extend({
    defaults: {
      adults: 1,
      children: 0,
      budget: 100000
    },
    initialize: function() {
      console.log('model ready bitchiz');
      return this;
    },
    sync: function() {
      return this;
    }
  });

  app.models.search = Search;

}).call(this);
