// Generated by CoffeeScript 1.4.0
(function() {
  var app, router;

  app = _.extend(this.app, Backbone.Events);

  app.dom = {};

  app.dom.win = $(window);

  app.dom.doc = $(document);

  app.dom.html = $('html');

  app.dom.body = $('body');

  app.dom.header = $('#l-header');

  app.dom.content = $('#l-content');

  app.modules = {};

  app.dom.html.removeClass('no-js').addClass('js');

  if (app.browser.isOpera) {
    app.dom.html.addClass('opera');
  }

  if (app.browser.isFirefox) {
    app.dom.html.addClass('firefox');
  }

  if (app.browser.isIE) {
    app.dom.html.addClass('ie ie' + app.browser.isIE);
  }

  if (app.browser.isIOS) {
    app.dom.html.addClass('ios ios' + app.browser.isIOS);
  }

  if (app.browser.isAndroid) {
    app.dom.html.addClass('android android' + app.browser.isAndroid);
  }

  app.socket = io.connect(app.env.host);

  router = new app.Router();

  Backbone.history.start({
    pushState: true
  });

  this.app = app;

}).call(this);
