// Generated by CoffeeScript 1.4.0
(function() {
  var Router;

  Router = Backbone.Router.extend({
    routes: {
      '': 'index',
      'search': 'search'
    },
    index: function() {
      app.log('[app.Router.index]: match');
      return new app.views.Index({
        model: new app.models.Search({
          trips: new app.collections.Trips()
        })
      });
    },
    search: function() {
      return app.log('[app.Router.search]: match');
    }
  });

  app.Router = Router;

}).call(this);
