// Generated by CoffeeScript 1.4.0
(function() {
  var Router;

  Router = Backbone.Router.extend({
    routes: {
      '': 'index'
    },
    index: function() {
      return new app.views.index({
        model: new app.models.search
      });
    }
  });

  app.router = Router;

}).call(this);
