// Generated by CoffeeScript 1.4.0
(function() {
  var Mongolian, airports, csv, db, objects, server;

  csv = require("csv");

  Mongolian = require("mongolian");

  server = new Mongolian();

  db = server.db("ostroterra");

  airports = db.collection("airports");

  objects = [];

  csv().from.path("airports.csv", {
    delimiter: ",",
    columns: null
  }).transform(function(data) {
    data.unshift(data.pop());
    return data;
  }).on("record", function(data, index) {
    var airportId, alt, city, country, iata, icao, lat, lon, name, timezone;
    airportId = data[1];
    name = data[2];
    city = data[3];
    country = data[4];
    iata = data[5];
    icao = data[6];
    lat = data[7];
    lon = data[8];
    alt = data[9];
    timezone = data[10];
    return objects.push({
      airportId: airportId,
      name: name,
      city: city,
      country: country,
      iata: iata,
      icao: icao,
      lat: lat,
      lon: lon,
      alt: alt,
      timezone: timezone
    });
  }).on("end", function(count) {
    console.log(">> Airports drop");
    airports.drop();
    console.log(">> Airports insert");
    airports.insert(objects);
    console.log(">> END");
    return process.exit();
  });

}).call(this);
