// Generated by LiveScript 1.2.0
(function(){
  var winston;
  winston = require("winston");
  exports.getLogger = function(name){
    var logger;
    logger = new (winston.Logger)({
      transports: [
        new (winston.transports.Console)({
          colorize: true,
          timestamp: true
        }), new (winston.transports.File)({
          filename: __dirname + ("/../../logs/" + name + ".log"),
          timestamp: true
        })
      ]
    });
    return logger;
  };
}).call(this);
