// Generated by LiveScript 1.2.0
(function(){
  var _, async, cache, database, moment, request, jsdom;
  _ = require("underscore");
  async = require("async");
  cache = require("./../../cache");
  database = require("./../../database");
  moment = require("moment");
  request = require("request");
  jsdom = require("jsdom").jsdom;
  exports.name = "airbnb.com";
  exports.search = function(origin, destination, extra, cb){
    var numPages, operations;
    numPages = 20;
    operations = _.map((function(){
      var i$, to$, results$ = [];
      for (i$ = 0, to$ = numPages; i$ < to$; ++i$) {
        results$.push(i$);
      }
      return results$;
    }()), function(i){
      return function(cb){
        var airUrl;
        airUrl = "https://m.airbnb.com/api/v1/listings/search?checkin=" + origin.date + "&checkout=" + destination.date + "&location=" + destination.place.name + "--" + destination.place.country_name + "&number_of_guests=" + extra.adults + "&offset=" + i * 20;
        return cache.request(airUrl, function(error, body){
          var json, results;
          if (error) {
            return cb(error, null);
          }
          try {
            json = JSON.parse(body);
          } catch (e$) {
            error = e$;
            return cb(error, null);
          }
          if (!json.listings) {
            return cb({
              message: 'no listings'
            }, null);
          }
          results = _.map(json.listings, function(r){
            var listing, days, hotel, dbHotel;
            listing = r.listing;
            days = moment.duration(moment(destination.date) - moment(origin.date)).days();
            hotel = {
              address: listing.address,
              id: listing.id,
              images: listing.picture_urls,
              latitude: listing.lat,
              longitude: listing.lng,
              name: listing.name,
              photo: listing.medium_url,
              price: listing.price * 30 * days,
              provider: exports.name,
              rating: null,
              reviews_count: listing.reviews_count,
              stars: null,
              type: 'apartment',
              url: "https://www.airbnb.com/rooms/" + listing.id
            };
            dbHotel = clone$(hotel);
            delete dbHotel.price;
            database.hotels.insert(dbHotel, function(error, hotel){});
            return hotel;
          });
          return cb(null, results);
        });
      };
    });
    return async.parallel(operations, function(error, results){
      if (error) {
        return cb(error, {});
      }
      return cb(null, {
        results: _.flatten(results),
        complete: true
      });
    });
  };
  exports.details = function(id, callback){
    return database.hotels.findOne({
      provider: exports.name,
      id: id
    }, function(error, hotel){
      var url;
      if (error || !hotel) {
        return callback(error, null);
      }
      if (!hotel.description) {
        url = "https://www.airbnb.com/rooms/" + id;
        return cache.request(url, function(error, airBnbPage){
          if (error) {
            return callback(error, null);
          }
          return cache.request("http://code.jquery.com/jquery.js", function(error, jQuery){
            if (error) {
              return callback(error, null);
            }
            return jsdom.env({
              html: airBnbPage,
              src: [jQuery],
              done: function(errors, window){
                if (errors) {
                  return callback(errors, null);
                }
                hotel.description = window.$('#description_text_wrapper').html();
                database.hotels.update({
                  _id: hotel._id
                }, {
                  $set: {
                    description: hotel.description
                  }
                }, true);
                delete hotel._id;
                return callback(null, hotel);
              }
            });
          });
        });
      } else {
        delete hotel._id;
        return callback(null, hotel);
      }
    });
  };
  function clone$(it){
    function fun(){} fun.prototype = it;
    return new fun;
  }
}).call(this);
